name: Java CI with Maven

# here we try to control when the workflow will run 
on:
  push:
    branches: ["main"] # Run on pushes to the main branch
  pull_request:
    branches: ["main"] # Run on pull requests targeting the main branch 

jobs:
  build:
    runs-on: ubuntu-latest # Specify the runner environement 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21 
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build and Test with Maven 
      run: mvn -B clean verify
